name: Build and test

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:

  build_x86-64:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        flags: [--all-features, --no-default-features]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust 1.73.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0
          override: true

      - name: Build
        run: cargo build --workspace ${{ matrix.flags }} --verbose

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install rust 1.73.0
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0
          override: true

      - name: Run all tests
        run: cargo test --workspace --all-features --verbose

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.73.0
          override: true
          components: rustfmt, clippy
      - run: rustup component add clippy
      - name: Check formatting
        run: cargo fmt -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-targets --all-features --workspace -- -D clippy::all